/** Shared English UI copy used across the site. */
export const UI = {
  previewComingSoon: "Preview coming soon",
  detailedDescription: "Detailed description",
  caseStudy: "Case Study",
  demo: "Demo",
  demoComingSoon: "Demo coming soon",
  showMore: (n) => `Show more (${n} other${n > 1 ? "s" : ""})`,
  showLess: "Show less",
  backToPortfolio: "Back to portfolio",
  viewOtherProjects: "View Other Projects",
  projectNotFound: "Project not found",
  projectNotFoundDesc: "This project does not exist. Return to the portfolio to see available projects.",
  caseStudyComingSoon: "The detailed case study for this project is coming soon. Here is the full description for now:",
  role: "Role",
  duration: "Duration",
  year: "Year",
  video: "Video",
  theProblem: "The Problem",
  goals: "Goals",
  mockups: "Mockups",
  challenges: "Challenges",
  solutions: "Solutions",
  screenshots: "Screenshots",
  results: "Results",
  learnings: "What I Learned",
  fillAllFields: "Please fill in all fields before sending.",
  toggleDarkMode: "Toggle dark mode",
  openMenu: "Open menu",
};
